# Welcome to Jekyll!
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Swig of Sake
email: raymondrrandy@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://swigofsake.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: raymadeit
github_username: raymadeit

# Build settings
markdown: kramdown
kramdown:
  input: GFM
gems:
  - jekyll-feed
  - jekyll-assets
sass:
  sass_dir: _sass
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
